# Problem 1 

In [ ]:
# 1 - numpy kütüphanesini import edin
import numpy as np

# 2 - 5 elemanlı bir numpy array oluşturun
dizi = np.array([12, 4, 9, 1, 7])
print("Orijinal dizi:", dizi)

# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın
sirali_dizi = np.sort(dizi)
print("Sıralanmış dizi:", sirali_dizi)



# Problem 2

In [1]:
import numpy as np

# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.
dizi1 = np.array([10, 15, 30, 45, 60])
print("1:", dizi1)

# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.
dizi2 = np.arange(5, 16)
print("2:", dizi2)

# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.
dizi3 = np.arange(50, 101, 5)
print("3:", dizi3)

# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.
dizi4 = np.zeros(10)
print("4:", dizi4)

# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.
dizi5 = np.ones(10)
print("5:", dizi5)

# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.
dizi6 = np.linspace(0, 100, 5)
print("6:", dizi6)

# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.
dizi7 = np.random.randint(10, 30, 5)
print("7:", dizi7)

# 8- [-1 ile 1] arasında 10 adet sayı üretin.
dizi8 = np.random.uniform(-1, 1, 10)
print("8:", dizi8)

# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.
matris9 = np.random.randint(10, 50, (3, 5))
print("9:\n", matris9)

# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ?
satir_toplamlari = matris9.sum(axis=1)
sutun_toplamlari = matris9.sum(axis=0)
print("10 - Satır toplamları:", satir_toplamlari)
print("10 - Sütun toplamları:", sutun_toplamlari)

# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?
en_buyuk = matris9.max()
en_kucuk = matris9.min()
ortalama = matris9.mean()
print("11 - En büyük:", en_buyuk, "En küçük:", en_kucuk, "Ortalama:", ortalama)

# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?
en_buyuk_indeks = np.unravel_index(matris9.argmax(), matris9.shape)
print("12 - En büyük değerin indeksi:", en_buyuk_indeks)

# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.
dizi13 = np.arange(10, 21)
ilk_uc_eleman = dizi13[:3]
print("13 - İlk 3 eleman:", ilk_uc_eleman)

# 14- Üretilen dizinin elemanlarını tersten yazdırın.
tersten = dizi13[::-1]
print("14 - Tersten yazılmış dizi:", tersten)

# 15- Üretilen matrisin ilk satırını seçiniz.
ilk_satir = matris9[0]
print("15 - İlk satır:", ilk_satir)

# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?
eleman_2satir_3sutun = matris9[1, 2]
print("16 - 2.satır 3.sütun elemanı:", eleman_2satir_3sutun)

# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.
tum_satirlar_ilk_eleman = matris9[:, 0]
print("17 - Tüm satırların ilk elemanları:", tum_satirlar_ilk_eleman)

# 18- Üretilen matrisin her bir elemanının karesini alınız.
kare_matris = matris9 ** 2
print("18 - Elemanların kareleri:\n", kare_matris)

# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.
matris19 = np.random.randint(-50, 51, (3, 5))
pozitif_ciftler = matris19[(matris19 > 0) & (matris19 % 2 == 0)]
print("19 - Matris:\n", matris19)
print("19 - Pozitif çift sayılar:", pozitif_ciftler)



1: [10 15 30 45 60]
2: [ 5  6  7  8  9 10 11 12 13 14 15]
3: [ 50  55  60  65  70  75  80  85  90  95 100]
4: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
5: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
6: [  0.  25.  50.  75. 100.]
7: [24 18 25 22 22]
8: [ 0.93552691 -0.93930501  0.11467625 -0.46246211  0.96713127  0.79578101
 -0.86518087 -0.46460993  0.54262539  0.83435356]
9:
 [[43 21 13 46 30]
 [13 28 36 38 13]
 [21 10 24 25 15]]
10 - Satır toplamları: [153 128  95]
10 - Sütun toplamları: [ 77  59  73 109  58]
11 - En büyük: 46 En küçük: 10 Ortalama: 25.066666666666666
12 - En büyük değerin indeksi: (np.int64(0), np.int64(3))
13 - İlk 3 eleman: [10 11 12]
14 - Tersten yazılmış dizi: [20 19 18 17 16 15 14 13 12 11 10]
15 - İlk satır: [43 21 13 46 30]
16 - 2.satır 3.sütun elemanı: 36
17 - Tüm satırların ilk elemanları: [43 13 21]
18 - Elemanların kareleri:
 [[1849  441  169 2116  900]
 [ 169  784 1296 1444  169]
 [ 441  100  576  625  225]]
19 - Matris:
 [[ 13  28  47   5  42]
 [  0  50   6 -30 -10]
 [  7 -30